"""
this file holds one of the jobs from rapidResults.json for the unit test in test.py
"""
test_data1 = {"id": "f97b4a007d08a432", "site": "indeed", "job_url":
              "https://www.indeed.com/viewjob?jk=f97b4a007d08a432", "job_url_direct":
              "http://www.indeed.com/job/information-security-analystsr-information-security-analyst-f97b4a007d08a432",
              "title": "Information Security Analyst/Sr. Information Security Analyst", "company":
              "School Employees Retirement System of Ohio", "location": "Columbus, OH, US", "job_type":
              "fulltime", "date_posted": "2024-09-05", "salary_source": "direct_data", "interval": "yearly",
              "min_amount": "71460.0", "max_amount": "123270.0", "currency": "USD", "is_remote": "True", "job_level":
              "", "job_function": "", "company_industry": "", "listing_type": "", "emails": "hr@ohsers.org",
              "description":
              "The School Employees Retirement System of Ohio (SERS) is seeking an **Information Security Analyst or"
              " Sr."
              " Information Security Analyst, based on experience.** We are looking for a person who is passionate"
              " about"
              " information security and extremely very detail oriented.\n\nThe desired candidate will have experience"
              " or"
              " training related to information security.\n\n**Requested Experience, Skills and Education**\n\n\u00b7"
              " Associates degree (A.A.) or higher in computer science or related field with;\n\n\u00b7 Experience in"
              " information security roles, with a focus on data loss prevention, fraud detection, and insider threat"
              " mitigation.\n\n\u00b7 Strong understanding of DLP technologies, including content inspection, data"
              " classification, and data encryption.\n\n\u00b7 Experience with fraud detection techniques and tools"
              ", such as anomaly detection, machine learning, and behavioral analytics.\n\n\u00b7 Understanding of"
              " insider threat monitoring and detection mechanisms, including user behavior analytics and privilege"
              " access management.\n\n\u00b7 Knowledge of regulatory requirements and industry standards related to"
              " data "
              "protection, fraud prevention, and insider threat mitigation.\n\n\u00b7 Excellent analytical and"
              " problem-solving"
              " skills, with attention to detail and the ability to think critically under pressure.\n\n\u00b7 Strong"
              " communication and interpersonal skills, with the ability to effectively convey complex technical"
              " concepts"
              " to non-technical stakeholders.\n\n\u00b7 Certifications in, or interest in pursuing, relevant industry"
              " certifications are highly desirable, such as:\n\n\u00b7 Carnegie Mellon - SEI Certificate in Insider"
              " Threat"
              " Program Manager (ITPM),\n\n\u00b7 Insider Threat Vulnerability Assessor (ITVA),\n\n\u00b7 Insider"
              " Threat"
              " Program Evaluator (ITPE),\n\n\u00b7 Certificate in Insider Risk Management and Mitigation,\n\n\u00b7"
              " SANS -"
              " SEC401/501, SEC504, SEC530, SEC566, SEC595 (combination of any of these) GIAC - GOSI, GMON, GCED, GCWN,"
              " GDSA,"
              " GISP, GCFR (combination of any of these),\n\n\u00b7 Certified Counter-Insider Threat Professional"
              " (CCITP-F or"
              " CCITP-A)\n\n\u00b7 Certified Information Systems Security Professional (CISSP), Certified Information"
              " Security"
              " Manager (CISM), Global Information Assurance Certification (GIAC), etc.\n\n\u00b7 Experience with"
              " security"
              " tools and technologies, such as SIEM, data classification, data protection, endpoint detection and"
              " response,"
              " is a plus.\n\n\u00b7 ***Equivalent combination of education, skills, and experience considered when"
              " evaluating"
              " candidates for the Information Security Analyst or Senior Information Security Analyst role"
              ".***\n\n**Location"
              " and Commitments**\n\n\u00b7 Hybrid work environment, offering 2-work from home days, each week,"
              " after 30 days"
              " of employment, or once eligible.\n\n\u00b7 Required onsite workdays take place in our office in"
              " downtown"
              " Columbus, with free parking.\n\n\u00b7 Core business hours are 8 to 4:45 PM (40 hours per week)"
              " Monday through"
              " Friday.\n\nTo view the full job description and to apply, please visit"
              " https://www.ohsers.org/about-sers/careers-at-sers/\n\nSERS is a defined benefit public pension fund"
              " that"
              " provides retirement allowances, disability and survivor benefits, and access to health care coverage"
              " for"
              " the people who served our schools. Our members are school bus drivers, custodians, secretaries,"
              " cafeteria workers, teacher\u2019s aides, administrative and support staff, treasurers, business"
              " managers, and school board members \u2013 anyone who works for a school or school system in a"
              " nonteaching position. Our office is located in Columbus, Ohio.\n\nSERS is an Equal Employment"
              " Opportunity Employer. We recruit, hire, train, and promote without discrimination due to age,"
              " race, color, religion, sex, sexual orientation, national origin, citizenship, disability,"
              " military leave or veteran status, genetic information, or any other status protected by"
              " applicable federal, state or local law.\n\nSERS is committed to ensuring all applicants can"
              " successfully submit an application for consideration. If you have a disability, and you wish"
              " to discuss potential accommodations to complete your application for employment, please send"
              " an email to hr@ohsers.org or call (614) 340-2255.\n\n**SERS does not accept unsolicited recruiter and"
              " agency"
              " resumes and will not pay fees to any third-party agency or company that does not have a signed"
              " agreement with"
              " SERS.**\n\nJob Type: Full-time\n\nPay: $71,460.00 - $123,270.00 per year\n\nBenefits:\n\n* Dental"
              " insurance\n*"
              " Flexible schedule\n* Health insurance\n* Paid time off\n* Parental leave\n* Vision insurance\n\nWork"
              " Location:"
              " In person", "company_url": "https://www.indeed.com/cmp/School-Employees-Retirement-System-of-Ohio-1",
              "company_url_direct": "http://ohsers.org/", "company_addresses": "", "company_num_employees": "",
              "company_revenue": "", "company_description": "", "logo_photo_url": "", "banner_photo_url": "",
              "ceo_name":
              "", "ceo_photo_url": ""}